package com.smhrd.model;

public class Ryan extends Charac{

	public Ryan() {
		super("라이언", 10, 5);
	}

	@Override
	public void printASCII() {
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMWNXNWWMMMMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMW0kO0KXNWWMMMMMMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMWXOkdxkO0KKKXXNNWWMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMWKdclodxkO0KKKKKXXXXXNWMMMMMMMMM\r\n"
				+ "MMMMMMMWOc;codxkkolloox0XXXXXXNWMMMMMMMM\r\n"
				+ "MMMMMMM0c,;cldxkOOoloodOXXXK0KXNMMMMMMMM\r\n"
				+ "MMMMMMNd,,;cloxkOkook0KKKXXOdod0WMMMMMMM\r\n"
				+ "MMMMMMKl,,;:lodxkO000KXOdkKKxod0WMMMMMMM\r\n"
				+ "MMMMMMXl,;;::loxxOkxx0WKoxXKkk0XWMMMMMMM\r\n"
				+ "MMMMMMWk:;;;::lodxdoldO0KNXK000NMMMMMMMM\r\n"
				+ "MMMMMMMNkc;;::cclooooddddkOOOOXWMMMMMMMM\r\n"
				+ "MMMMMMMMWKxl;;:clllooooddxxxOXWMMMMMMMMM\r\n"
				+ "MMMMMMMMMMWk;;okOkdlllllodkKNMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMXl,:x0KKOkxkO000XWMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMWk;,cx0K0000OkOkOKNMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMNo,,:dO0000K0kxdx0NMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMNkdddk0XXKKXXKKKKNWMMMMMMMMMMMM\r\n"
				+ "MMMMMMMMMMMMMMWWMWWWWMMMMMMMMMMMMMMMMMMM");
		
	}
	

}
